fix an error while using avalon_framework 1.6.2
AttributeError: module 'avalon_framework' has no attribute 'error'  popup when avalon_framework 1.6.2 is used.